echo "*** straight ***"
echo "python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 5e-3"
python train_ildist.py --scenario intersection --goal straight --epochs 100 --lr 5e-3
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore
python train_ildist.py --scenario intersection --goal straight --epochs 1000 --lr 1e-5  --restore

echo "*** right ***"
echo "python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 5e-3"
python train_ildist.py --scenario intersection --goal right --epochs 3 --lr 5e-3
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal right --epochs 1000 --lr 1e-5 --restore


echo "*** left ***"
echo "python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 5e-3"
python train_ildist.py --scenario intersection --goal left --epochs 2 --lr 5e-3 
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore
python train_ildist.py --scenario intersection --goal left --epochs 1000 --lr 1e-5 --restore